name: Run manual workflow

on:
  workflow_dispatch:
    inputs:
      my-var:
        description: "This my txt var"
        default: 'tmp'
      repository:
        description: "Select the repository"
        type: choice
        options:
           - spring-boot-cicd
           - SimpleSpringBoot
#      repository2:
#        type: choice
#        options:
#          # Use the GitHub API to list all your repositories.
#          - {{ github.repository_list }}
env:
  # Setting an environment variable with the value of a configuration variable
  env_var: ${{ vars.ENV_CONTEXT_VAR }}

jobs:
  job-1-checkout-repositories:
    name: Job 1 - Checkout repositories
    runs-on: ubuntu-latest
    steps:
      - name: Job 1 - Step 1 - Print inputs
        id: job-1-step-1
        run: |
          echo "My var = ${{ github.event.inputs.my-var }}"
          echo "repository = ${{ github.event.inputs.repository }}"
          echo "repository variable : $REPOSITORY_VAR"
          echo "organization variable : $ORGANIZATION_VAR"
          echo "overridden variable : $OVERRIDE_VAR"
          echo "variable from shell environment : $env_var"
        shell: bash